branches:
  only:
    - develop
    - master
language: swift
osx_image: xcode8.3
before_install:
  - rvm use $RVM_RUBY_VERSION
  - pod repo update
  - pod install

script:
  - set -o pipefail && xcodebuild clean -workspace DancingSteps.xcworkspace -scheme DancingSteps -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
