branches:
  only:
    - develop
    - master
language: swift
osx_image: xcode8.3
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - pod repo update
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace DancingSteps.xcworkspace -scheme DancingSteps -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint
